// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPmGRxlh_9S9rgwF8EMTHY60w3CbrJiiY',
    appId: '1:292364051513:web:cea1e64df9574df46619e8',
    messagingSenderId: '292364051513',
    projectId: 'jaehyeok-20871',
    authDomain: 'jaehyeok-20871.firebaseapp.com',
    storageBucket: 'jaehyeok-20871.appspot.com',
    measurementId: 'G-J2X68C2PYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQLRIW99TG8Q4shSf7mtC2ir6VX1JCD7Y',
    appId: '1:292364051513:android:c3fc9242c338f3806619e8',
    messagingSenderId: '292364051513',
    projectId: 'jaehyeok-20871',
    storageBucket: 'jaehyeok-20871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeh-9CuTZp0viXPNWch_RwqSMRnDy3cZs',
    appId: '1:292364051513:ios:3573fda9e0622d656619e8',
    messagingSenderId: '292364051513',
    projectId: 'jaehyeok-20871',
    storageBucket: 'jaehyeok-20871.appspot.com',
    iosClientId: '292364051513-j7941gq1gek5k1864esgnopntkfthd2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.jaeMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeh-9CuTZp0viXPNWch_RwqSMRnDy3cZs',
    appId: '1:292364051513:ios:3573fda9e0622d656619e8',
    messagingSenderId: '292364051513',
    projectId: 'jaehyeok-20871',
    storageBucket: 'jaehyeok-20871.appspot.com',
    iosClientId: '292364051513-j7941gq1gek5k1864esgnopntkfthd2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.jaeMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPmGRxlh_9S9rgwF8EMTHY60w3CbrJiiY',
    appId: '1:292364051513:web:022b214aa7e128176619e8',
    messagingSenderId: '292364051513',
    projectId: 'jaehyeok-20871',
    authDomain: 'jaehyeok-20871.firebaseapp.com',
    storageBucket: 'jaehyeok-20871.appspot.com',
    measurementId: 'G-GWH2M0LMLW',
  );

}